<a href="https://colab.research.google.com/github/kanchan874/pattern_recognition/blob/main/Practical1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler
from sklearn.metrics.pairwise import (
    euclidean_distances,
    manhattan_distances,
    cosine_similarity
)

In [2]:
from google.colab import files

uploaded = files.upload()

Saving Online Retail.xlsx to Online Retail.xlsx

In [3]:
df = pd.read_excel("Online Retail.xlsx")

print("Dataset Shape:", df.shape)
df.head()

Dataset Shape: (541909, 8)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [4]:
# Remove rows with missing CustomerID
df = df.dropna(subset=['CustomerID'])

# Create TotalAmount column
df['TotalAmount'] = df['Quantity'] * df['UnitPrice']

print(df.head())

  InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365     71053                  WHITE METAL LANTERN         6
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6

          InvoiceDate  UnitPrice  CustomerID         Country  TotalAmount
0 2010-12-01 08:26:00       2.55     17850.0  United Kingdom        15.30
1 2010-12-01 08:26:00       3.39     17850.0  United Kingdom        20.34
2 2010-12-01 08:26:00       2.75     17850.0  United Kingdom        22.00
3 2010-12-01 08:26:00       3.39     17850.0  United Kingdom        20.34
4 2010-12-01 08:26:00       3.39     17850.0  United Kingdom        20.34

In [5]:
customer_profile = df.groupby('CustomerID').agg({
    'Quantity':'sum',
    'TotalAmount':'sum',
    'InvoiceNo':'nunique'
}).reset_index()

customer_profile.columns = [
    'CustomerID',
    'TotalQuantity',
    'TotalSpending',
    'TotalOrders'
]

customer_profile.head()

   CustomerID  TotalQuantity  TotalSpending  TotalOrders
0     12346.0              0           0.00            2
1     12347.0           2458        4310.00            7
2     12348.0           2341        1797.24            4
3     12349.0            631        1757.55            1
4     12350.0            197         334.40            1

In [6]:
features = customer_profile[
    ['TotalQuantity','TotalSpending','TotalOrders']
]

scaler = StandardScaler()

scaled_features = scaler.fit_transform(features)

print(scaled_features[:5])

[[-0.24021456 -0.23100099 -0.32936215]
 [ 0.28586959  0.29343167  0.20610242]
 [ 0.26082816 -0.01231622 -0.11517632]
 [-0.10516204 -0.01714563 -0.43645506]
 [-0.19805078 -0.19031183 -0.43645506]]

In [7]:
euclidean_matrix = euclidean_distances(scaled_features)

euclidean_df = pd.DataFrame(euclidean_matrix)

print("Euclidean Distance Matrix")
euclidean_df.head()

Euclidean Distance Matrix

,0,1,2,3,4,5,6,7,8,9,...,4362,4363,4364,4365,4366,4367,4368,4369,4370,4371
0,0.000000,0.915705,0.587148,0.274667,0.122075,0.987147,0.107724,0.203928,0.131271,0.494417,...,0.111257,0.000000,0.120697,0.018621,0.110073,0.109748,0.108163,0.111223,1.549928,0.420325
1,0.915705,0.000000,0.444217,0.813784,0.938652,0.691160,0.974139,0.858884,0.926153,0.501184,...,0.831958,0.915705,0.809748,0.900730,0.963465,0.965436,0.970788,0.831619,1.026253,0.555752
2,0.587148,0.444217,0.000000,0.487024,0.587769,0.850455,0.627054,0.510968,0.576131,0.229052,...,0.532194,0.587148,0.506717,0.570547,0.615893,0.619193,0.621638,0.529925,1.301405,0.193919
3,0.274667,0.813784,0.487024,0.000000,0.196507,1.071794,0.241497,0.085301,0.178755,0.323321,...,0.309058,0.274667,0.292373,0.258524,0.227497,0.229235,0.238486,0.309668,1.615260,0.296223
4,0.122075,0.938652,0.587769,0.196507,0.000000,1.082597,0.048236,0.115313,0.017777,0.475115,...,0.216228,0.122075,0.214208,0.114337,0.034169,0.037531,0.043460,0.216086,1.640839,0.409506

In [8]:
manhattan_matrix = manhattan_distances(scaled_features)

manhattan_df = pd.DataFrame(manhattan_matrix)

print("Manhattan Distance Matrix")
manhattan_df.head()

Manhattan Distance Matrix

,0,1,2,3,4,5,6,7,8,9,...,4362,4363,4364,4365,4366,4367,4368,4369,4370,4371
0,0.000000,1.585981,0.933913,0.456001,0.189946,1.252473,0.122203,0.351868,0.214359,0.789703,...,0.149038,0.000000,0.185820,0.026219,0.142379,0.138699,0.128485,0.149556,2.053201,0.670100
1,1.585981,0.000000,0.652068,1.344166,1.610221,1.190252,1.677964,1.448299,1.585808,0.796278,...,1.436944,1.585981,1.400161,1.559762,1.657789,1.661468,1.671683,1.436425,1.460453,0.915881
2,0.933913,0.652068,0.000000,0.692098,0.958153,1.180742,1.025896,0.796231,0.933740,0.391020,...,0.784876,0.933913,0.748093,0.907694,1.005720,1.009400,1.019615,0.784357,1.523375,0.273557
3,0.456001,1.344166,0.692098,0.000000,0.266055,1.131201,0.333798,0.104133,0.241642,0.547888,...,0.521149,0.456001,0.484366,0.429781,0.313622,0.317301,0.327516,0.520630,1.811386,0.428285
4,0.189946,1.610221,0.958153,0.266055,0.000000,1.276713,0.067743,0.161922,0.024413,0.813943,...,0.255094,0.189946,0.218312,0.163726,0.047567,0.051247,0.061461,0.254576,2.077441,0.694340

In [9]:
cosine_matrix = cosine_similarity(scaled_features)

cosine_df = pd.DataFrame(cosine_matrix)

print("Cosine Similarity Matrix")
cosine_df.head()

Cosine Similarity Matrix

,0,1,2,3,4,5,6,7,8,9,...,4362,4363,4364,4365,4366,4367,4368,4369,4370,4371
0,1.000000,-0.950958,-0.163585,0.821693,0.973760,-0.542540,0.988024,0.904649,0.966790,0.186772,...,0.988980,1.000000,0.994555,0.999585,0.984479,0.985093,0.986994,0.989211,-0.737678,0.447726
1,-0.950958,1.000000,0.360726,-0.606940,-0.855918,0.262072,-0.891872,-0.728477,-0.840456,0.125817,...,-0.985337,-0.950958,-0.977773,-0.941827,-0.881949,-0.883572,-0.889138,-0.985732,0.493098,-0.175735
2,-0.163585,0.360726,1.000000,0.179780,0.006496,-0.586425,-0.055240,0.138783,0.021912,0.658966,...,-0.279726,-0.163585,-0.240632,-0.140616,-0.040101,-0.047710,-0.043124,-0.270293,-0.358007,0.742076
3,0.821693,-0.606940,0.179780,1.000000,0.926185,-0.893988,0.898360,0.983210,0.937088,0.702365,...,0.733288,0.821693,0.759933,0.836814,0.907339,0.906538,0.899794,0.732053,-0.982566,0.792443
4,0.973760,-0.855918,0.006496,0.926185,1.000000,-0.718066,0.997157,0.977584,0.999548,0.405272,...,0.929537,0.973760,0.944751,0.979877,0.998521,0.998202,0.997678,0.929920,-0.871907,0.627248

In [10]:
customer_index = 0

similarity_scores = cosine_matrix[customer_index]

similar_customers = pd.DataFrame({
    'CustomerID': customer_profile['CustomerID'],
    'Similarity': similarity_scores
})

similar_customers = similar_customers.sort_values(
    by='Similarity',
    ascending=False
)

similar_customers.head(10)

      CustomerID  Similarity
4363     18274.0         1.0
89       12454.0         1.0
1059     13762.0         1.0
1642     14557.0         1.0
3349     16878.0         1.0
1809     14792.0         1.0
775      13364.0         1.0
0        12346.0         1.0
170      12558.0         1.0
4358     18268.0         1.0

In [11]:
def edit_distance(str1, str2):

    m = len(str1)
    n = len(str2)

    dp = [[0]*(n+1) for _ in range(m+1)]

    for i in range(m+1):
        dp[i][0] = i

    for j in range(n+1):
        dp[0][j] = j

    for i in range(1, m+1):
        for j in range(1, n+1):

            if str1[i-1] == str2[j-1]:
                dp[i][j] = dp[i-1][j-1]

            else:
                dp[i][j] = 1 + min(
                    dp[i][j-1],
                    dp[i-1][j],
                    dp[i-1][j-1]
                )

    return dp[m][n]

In [12]:
product1 = "WHITE HANGING HEART T-LIGHT HOLDER"
product2 = "WHITE METAL LANTERN"

distance = edit_distance(product1, product2)

print("Product 1:", product1)
print("Product 2:", product2)
print("Edit Distance =", distance)

Product 1: WHITE HANGING HEART T-LIGHT HOLDER
Product 2: WHITE METAL LANTERN
Edit Distance = 23