<a href="https://colab.research.google.com/github/kanchan874/pattern_recognition/blob/main/Practical2_PR_CM23004.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

In [2]:
from google.colab import files

uploaded = files.upload()

Saving diabetes.csv to diabetes.csv

In [3]:
df = pd.read_csv("diabetes.csv")

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [4]:
print(df.shape)

df.info()

df.describe()

(768, 9)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [5]:
X = df.drop("Outcome", axis=1)

y = df["Outcome"]

print(X.head())

   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6
1            1       85             66             29        0  26.6
2            8      183             64              0        0  23.3
3            1       89             66             23       94  28.1
4            0      137             40             35      168  43.1

   DiabetesPedigreeFunction  Age
0                     0.627   50
1                     0.351   31
2                     0.672   32
3                     0.167   21
4                     2.288   33

In [6]:
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y,
    test_size=0.2,
    random_state=42
)

In [8]:
model = LogisticRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy without PCA/LDA :",
      accuracy_score(y_test, y_pred))

Accuracy without PCA/LDA : 0.7532467532467533

In [9]:
pca = PCA(n_components=2)

X_pca = pca.fit_transform(X_scaled)

print("Original Shape :", X_scaled.shape)
print("Reduced Shape :", X_pca.shape)

Original Shape : (768, 8)
Reduced Shape : (768, 2)

In [10]:
print("Explained Variance Ratio:")

print(pca.explained_variance_ratio_)

print("Total Variance Explained:")

print(sum(pca.explained_variance_ratio_))

Explained Variance Ratio:
[0.26179749 0.21640127]
Total Variance Explained:
0.47819876073856576

In [11]:
X_train_pca, X_test_pca, y_train, y_test = train_test_split(
    X_pca,
    y,
    test_size=0.2,
    random_state=42
)

model_pca = LogisticRegression()

model_pca.fit(X_train_pca, y_train)

pred_pca = model_pca.predict(X_test_pca)

print("Accuracy after PCA :")

print(accuracy_score(y_test, pred_pca))

Accuracy after PCA :
0.7077922077922078

In [12]:
lda = LinearDiscriminantAnalysis(n_components=1)

X_lda = lda.fit_transform(X_scaled, y)

print("Original Shape :", X_scaled.shape)

print("Reduced Shape :", X_lda.shape)

Original Shape : (768, 8)
Reduced Shape : (768, 1)

In [13]:
X_train_lda, X_test_lda, y_train, y_test = train_test_split(
    X_lda,
    y,
    test_size=0.2,
    random_state=42
)

model_lda = LogisticRegression()

model_lda.fit(X_train_lda, y_train)

pred_lda = model_lda.predict(X_test_lda)

print("Accuracy after LDA :")

print(accuracy_score(y_test, pred_lda))

Accuracy after LDA :
0.7922077922077922

In [14]:
print("Classification Report (LDA)\n")

print(classification_report(y_test, pred_lda))

Classification Report (LDA)

              precision    recall  f1-score   support

           0       0.83      0.86      0.84        99
           1       0.73      0.67      0.70        55

    accuracy                           0.79       154
   macro avg       0.78      0.77      0.77       154
weighted avg       0.79      0.79      0.79       154

In [15]:
baseline = accuracy_score(y_test, y_pred)
pca_acc = accuracy_score(y_test, pred_pca)
lda_acc = accuracy_score(y_test, pred_lda)

comparison = pd.DataFrame({
    "Method": ["Original Features", "PCA", "LDA"],
    "Accuracy": [baseline, pca_acc, lda_acc]
})

comparison

              Method  Accuracy
0  Original Features  0.753247
1                PCA  0.707792
2                LDA  0.792208